name: CI/CD to Google Cloud

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: europe-west3 # Укажи тот же, что в Artifact Registry
  SERVICE_NAME: predict-sales-api
  REPO_NAME: sales-repo

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.5'
        cache: 'pip'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest
    - name: Download Data
      env:
        GOOGLE_DRIVE_FILE_ID: ${{ secrets.GOOGLE_DRIVE_FILE_ID }}
      run: |
        mkdir -p data
        curl -L -o data/df_final1.csv "https://drive.google.com/uc?export=download&id=${GOOGLE_DRIVE_FILE_ID}"
    - name: Run tests
      run: |
        if [ -d "tests" ]; then python -m pytest tests/; fi
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: data-csv
        path: data/df_final1.csv

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: data-csv
        path: data/

    # Авторизация в Google Cloud
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    # Настройка Docker для работы с Google Registry
    - name: Configure Docker
      run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

    # Сборка и Пуш образа
    - name: Build and Push
      run: |
        IMAGE_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"
        docker build -t $IMAGE_TAG .
        docker push $IMAGE_TAG

    # ДЕПЛОЙ В CLOUD RUN
    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ env.SERVICE_NAME }}
        region: ${{ env.REGION }}
        image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
        flags: '--allow-unauthenticated --memory=2Gi'

    - name: Show Output
      run: echo "Приложение запущено по адресу ${{ steps.deploy.outputs.url }}"